name: nginx-etl

services:
  nginx-etl:
    build:
      context: ../../
      dockerfile: deployments/dev/nginx_etl/Dockerfile
      tags:
        - "nginx-etl:dev"
    container_name: nginx-etl-cli
    labels:
      deployment: dev
    volumes:
      - ../..:/app
      - nginx-etl-data:/run/app
      - ./nginx:/run/nginx
    depends_on:
      clickhouse:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      REDIS_URL: redis://redis:6379/0

      CLICKHOUSE_HOST: clickhouse
      CLICKHOUSE_PORT: 8123
      CLICKHOUSE_USER: nginx-etl
      CLICKHOUSE_PASSWORD: nginx-etl
      CLICKHOUSE_DB: main

      NGINX_LOG_FILE_PATH: /run/nginx/fake.log
      NGINX_LOG_FILE_LINE_BATCH_MAX_SIZE: 5
    command: bash

  clickhouse:
    image: clickhouse:25.1.5.31-jammy
    container_name: nginx-etl-clickhouse
    labels:
      deployment: dev
    environment:
      CLICKHOUSE_PASSWORD: nginx-etl
      CLICKHOUSE_USER: nginx-etl
      CLICKHOUSE_DB: main
    volumes:
      - clickhouse-data:/var/lib/clickhouse
    ports:
      - 8123:8123
    healthcheck:
      test: clickhouse-client -d main -u nginx-etl --password nginx-etl -h clickhouse -q "SELECT 1"
      start_period: 1m
      start_interval: 1s
      interval: 5s

  redis:
    image: redis:7.4.1-alpine3.20
    container_name: nginx-etl-redis
    labels:
      deployment: dev
    volumes:
      - redis-data:/data
      - ./redis:/mnt
    command: redis-server /mnt/redis.conf
    healthcheck:
      test: echo PING | redis-cli | grep -qF PONG
      start_period: 1m
      start_interval: 0.5s
      interval: 1s

volumes:
  nginx-etl-data: null

  clickhouse-data:
    labels:
      db: true
      deployment: dev

  redis-data:
    labels:
      db: true
      deployment: dev
